import Head from "next/head";
import Image from "next/image";
import { BsFillSunFill } from "react-icons/bs";
import { FaMoon } from "react-icons/fa";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import expenseApp from "../../public/Images/expense-tracker.png";
import forkifyApp from "../../public/Images/forkify.png";
import omnifoodApp from "../../public/Images/omnifood.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const classNameSkills = () => {
    return "bg-secondary text-white py-2 px-4 rounded-2xl";
  };

  const portfolioClass = () => {
    return "text-center border shadow-lg overflow-hidden rounded-2xl transition hover:-translate-y-1 hover:scale-110";
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ananda Fitri Namira</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className={`text-xl ${darkMode ? "text-white" : ""}`}>
              AnandaF.
            </h1>
            <ul className="flex items-center gap-2">
              <li className="cursor-pointer">
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="text-xl text-white"
                  />
                ) : (
                  <FaMoon
                    onClick={() => setDarkMode(!darkMode)}
                    className="text-xl"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-primary text-white py-2 px-4 rounded-full ml-8"
                  href="https://drive.google.com/file/d/1qihkbR8-6OaOhkF-taJR8a7gP3oPJd8h/view"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-primary font-bold">
              Ananda Fitri Namira
            </h2>
            <h3 className={`text-2xl py-2 ${darkMode ? "text-white" : ""}`}>
              Web developer
            </h3>
            <p
              className={`text-md py-5 leading-8 ${
                darkMode ? "text-white" : "text-gray-700"
              } `}
            >
              Love to write a code to build a beautiful web app
            </p>
          </div>
          <div className="text-4xl flex justify-center gap-16 py-3 text-gray-500">
            <a
              target="_blank"
              href="https://www.linkedin.com/in/ananda-fitri-namira/"
            >
              <AiFillLinkedin className={`${darkMode ? "text-white" : ""}`} />
            </a>
            <a target="_blank" href="https://github.com/anandafn">
              <AiFillGithub className={`${darkMode ? "text-white" : ""}`} />
            </a>
          </div>
        </section>

        {/* Skills */}
        <section>
          <div className="mb-10">
            <h3
              className={`text-3xl text-center py-1 font-semibold ${
                darkMode ? "text-white" : "text-gray-700"
              } `}
            >
              Skills
            </h3>
            <div className="flex justify-center gap-6 ">
              <div className={classNameSkills()}>HTML</div>
              <div className={classNameSkills()}>CSS</div>
              <div className={classNameSkills()}>javascript</div>
              <div className={classNameSkills()}>ReactJS</div>
              <div className={classNameSkills()}>Redux</div>
              <div className={classNameSkills()}>TailwindCSS</div>
            </div>
          </div>
        </section>

        {/* Portfolios */}
        <section className="pb-8">
          <div>
            <h3
              className={`text-3xl text-center py-2 font-semibold ${
                darkMode ? "text-white" : "text-gray-700"
              } `}
            >
              Portfolios
            </h3>
          </div>
          <div className="grid lg:grid-cols-3 md:grid-cols-2 sm:grod-cols-1 gap-6 justify-center">
            <div className={portfolioClass()}>
              <a
                href="https://omnifood-web-portfolio.netlify.app/"
                target="_blank"
              >
                <Image
                  src={omnifoodApp}
                  alt="Omnifood App"
                  width={325}
                  height={325}
                  className="mb-4 mx-auto border-b"
                />
                <p
                  className={`font-bold ${
                    darkMode ? "text-white" : "text-gray-500"
                  }`}
                >
                  Omnifood App
                </p>
              </a>
              <div className="grid lg:grid-cols-2 md:grid-cols-2 py-4 px-8 gap-3">
                <div className={classNameSkills()}>HTML</div>
                <div className={classNameSkills()}>CSS</div>
                <div className={classNameSkills()}>javascript</div>
              </div>
            </div>
            <div className={portfolioClass()}>
              <a
                href="https://forkify-recipes-nanda.netlify.app/"
                target="_blank"
              >
                <Image
                  src={forkifyApp}
                  alt="Forkify App"
                  width={325}
                  height={325}
                  className="mb-4 mx-auto border-b"
                />
                <p
                  className={`font-bold ${
                    darkMode ? "text-white" : "text-gray-500"
                  }`}
                >
                  Forkify App
                </p>
              </a>
              <div className="grid lg:grid-cols-2 md:grid-cols-2 py-4 px-8 gap-3">
                <div className={classNameSkills()}>HTML</div>
                <div className={classNameSkills()}>CSS</div>
                <div className={classNameSkills()}>javascript</div>
                <div className={classNameSkills()}>API</div>
              </div>
            </div>
            <div className={portfolioClass()}>
              <a
                href="https://kaleidoscopic-frangollo-75d639.netlify.app/"
                target="_blank"
              >
                <Image
                  src={expenseApp}
                  alt="Expense App"
                  width={325}
                  height={325}
                  className="mb-4 mx-auto border-b"
                />
                <p
                  className={`font-bold ${
                    darkMode ? "text-white" : "text-gray-500"
                  }`}
                >
                  Expense Tracker App
                </p>
              </a>
              <div className="grid lg:grid-cols-2 md:grid-cols-2 py-4 px-8 gap-3">
                <div className={classNameSkills()}>HTML</div>
                <div className={classNameSkills()}>CSS</div>
                <div className={classNameSkills()}>javascript</div>
                <div className={classNameSkills()}>ReactJS</div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
